// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7plpmZjV-uX-d2OdD71iysES-O5bZ5EY',
    appId: '1:8086986211:web:4e9512dfadbebf73ce14d6',
    messagingSenderId: '8086986211',
    projectId: 'tiktok-b4410',
    authDomain: 'tiktok-b4410.firebaseapp.com',
    storageBucket: 'tiktok-b4410.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE3yVSCH7_9Fvbkx_q7f9sTIK3u-B5pho',
    appId: '1:8086986211:android:449ab40e959a6ef9ce14d6',
    messagingSenderId: '8086986211',
    projectId: 'tiktok-b4410',
    storageBucket: 'tiktok-b4410.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATBQ9f3PozcSSzdJc_-9oXG7Gm1bL41B0',
    appId: '1:8086986211:ios:e6a93ed95ec57f1ece14d6',
    messagingSenderId: '8086986211',
    projectId: 'tiktok-b4410',
    storageBucket: 'tiktok-b4410.appspot.com',
    iosClientId: '8086986211-7qf5l38ltqih4glhnauqm4r2dqh5ke4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
